In [1]:
import pandas as pd
import numpy as np
# Ignore harmless warnings 

import warnings 
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv(r"Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [4]:
data.shape

(10000, 14)

In [5]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis = 1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
#Encoding Categorical variable Geography and Gender

from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
data['Geography'] = Le.fit_transform(data['Geography'])
data['Gender'] = Le.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [7]:
data.describe()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,0.746300,0.545700,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,0.827529,0.497932,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,0.000000,0.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,0.000000,0.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,0.000000,1.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,1.000000,1.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,2.000000,1.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [8]:
#Splitting dataset into training and testing dataset

x = data.drop(['Exited'],axis = 1)
y = data['Exited']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((8000, 10), (2000, 10), (8000,), (2000,))

In [9]:
#Performing Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
#import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense

#Build the ANN model
#model = tf.keras.models.Sequential()
model = Sequential()

# Add input layer and first hidden layer
#model.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
model.add(Dense(units = 6,activation = 'relu',input_dim = X_train.shape[1]))

#Add second hidden layer
#model.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
model.add(Dense(units = 6, activation = 'relu'))

#Add output layer
#for multiclass classification, activation function = softmax
#model.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))
model.add(Dense(units = 1, activation = 'sigmoid'))

#Compiling ANN
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [11]:
#Train the ANN model
model.fit(X_train,Y_train,batch_size = 32,epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - accuracy: 0.6918 - loss: 0.6034
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 297us/step - accuracy: 0.7934 - loss: 0.4718
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8099 - loss: 0.4361
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 296us/step - accuracy: 0.8099 - loss: 0.4282
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 297us/step - accuracy: 0.8158 - loss: 0.4116
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - accuracy: 0.8222 - loss: 0.4094
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8253 - loss: 0.3942
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 298us/step - accuracy: 0.8225 - loss: 0.3994
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - accuracy: 0.8503 - loss: 0.3595
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - accuracy: 0.8478 - loss: 0.3611
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - accuracy: 0.8484 - loss: 0.3637
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - accuracy: 0.8557 - loss: 0.3522
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 303us/step - accuracy: 0.8606 - loss: 0.3404
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 301us/step - accuracy: 0.8605 - loss: 0.3405
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 301us/step - accuracy: 0.8565 - loss: 0.3438
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.8677 - loss: 0.3319
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - accuracy: 0.8569 - loss: 0.3409
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - accuracy: 0.8668 - loss: 0.3361
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - accuracy: 0.8670 - loss: 0.3310
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 298us/step - accuracy: 0.8614 - loss: 0.3392
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 296us/step - accuracy: 0.8569 - loss: 0.3471
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 294us/step - accuracy: 0.8612 - loss: 0.3383
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 296us/step - accuracy: 0.8572 - loss: 0.3423
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 307us/step - accuracy: 0.8577 - loss: 0.3456
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 309us/step - accuracy: 0.8616 - loss: 0.3378
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 304us/step - accuracy: 0.8637 - loss: 0.3297
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 299us/step - accuracy: 0.8609 - loss: 0.3446
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.8603 - loss: 0.3422
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - accuracy: 0.8594 - loss: 0.3477
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - accuracy: 0.8667 - loss: 0.3299
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 305us/step - accuracy: 0.8604 - loss: 0.3410
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 305us/step - accuracy: 0.8649 - loss: 0.3348
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - accuracy: 0.8619 - loss: 0.3402
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 309us/step - accuracy: 0.8597 - loss: 0.3458
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - accuracy: 0.8594 - loss: 0.3383
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - accuracy: 0.8595 - loss: 0.3390
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 308us/step - accuracy: 0.8573 - loss: 0.3419
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 307us/step - accuracy: 0.8671 - loss: 0.3311
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - accuracy: 0.8632 - loss: 0.3367
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - accuracy: 0.8576 - loss: 0.3469
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.8640 - loss: 0.3260
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 309us/step - accuracy: 0.8665 - loss: 0.3303
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - accuracy: 0.8701 - loss: 0.3287
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 307us/step - accuracy: 0.8623 - loss: 0.3396
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 307us/step - accuracy: 0.8566 - loss: 0.3399
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 302us/step - accuracy: 0.8648 - loss: 0.3352
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - accuracy: 0.8660 - loss: 0.3243
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - accuracy: 0.8718 - loss: 0.3252
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.8609 - loss: 0.3333
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 309us/step - accuracy: 0.8563 - loss: 0.3459
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - accuracy: 0.8687 - loss: 0.3269
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 316us/step - accuracy: 0.8732 - loss: 0.3178
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.8685 - loss: 0.3294
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.8573 - loss: 0.3418
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - accuracy: 0.8629 - loss: 0.3311
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 308us/step - accuracy: 0.8660 - loss: 0.3294
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 308us/step - accuracy: 0.8718 - loss: 0.3215
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 301us/step - accuracy: 0.8656 - loss: 0.3282
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 304us/step - accuracy: 0.8664 - loss: 0.3279
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 303us/step - accuracy: 0.8677 - loss: 0.3238
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 305us/step - accuracy: 0.8609 - loss: 0.3308
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 302us/step - accuracy: 0.8743 - loss: 0.3188
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 301us/step - accuracy: 0.8581 - loss: 0.3373
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 301us/step - accuracy: 0.8617 - loss: 0.3360
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 301us/step - accuracy: 0.8620 - loss: 0.3298
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 303us/step - accuracy: 0.8583 - loss: 0.3426
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 304us/step - accuracy: 0.8648 - loss: 0.3280
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - accuracy: 0.8734 - loss: 0.3177
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8660 - loss: 0.3274
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 293us/step - accuracy: 0.8660 - loss: 0.3270
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8653 - loss: 0.3247
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8657 - loss: 0.3365
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - accuracy: 0.8635 - loss: 0.3307
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8603 - loss: 0.3428
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 294us/step - accuracy: 0.8560 - loss: 0.3417
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - accuracy: 0.8617 - loss: 0.3386
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8597 - loss: 0.3380
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8604 - loss: 0.3442
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8602 - loss: 0.3484
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8682 - loss: 0.3190
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - accuracy: 0.8652 - loss: 0.3329
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 294us/step - accuracy: 0.8613 - loss: 0.3352
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 293us/step - accuracy: 0.8638 - loss: 0.3341
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 288us/step - accuracy: 0.8657 - loss: 0.3318
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8655 - loss: 0.3263
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8630 - loss: 0.3364
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.8667 - loss: 0.3283
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8578 - loss: 0.3382
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 293us/step - accuracy: 0.8651 - loss: 0.3303
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 293us/step - accuracy: 0.8666 - loss: 0.3294
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 297us/step - accuracy: 0.8691 - loss: 0.3267
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 294us/step - accuracy: 0.8659 - loss: 0.3329
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 293us/step - accuracy: 0.8620 - loss: 0.3312
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - accuracy: 0.8650 - loss: 0.3231
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - accuracy: 0.8638 - loss: 0.3235
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 293us/step - accuracy: 0.8674 - loss: 0.3275
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - accuracy: 0.8602 - loss: 0.3306
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8676 - loss: 0.3244
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8599 - loss: 0.3347
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - accuracy: 0.8597 - loss: 0.3366

In [12]:
#Predictions on the test set
Y_pred = model.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(Y_pred)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step
[[False]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]

In [13]:
#Accuracy of the model
from sklearn.metrics import accuracy_score,confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(Y_test,Y_pred))
print("Accuracy Score:",round(accuracy_score(Y_test,Y_pred)*100,2),'%')

Confusion Matrix:
[[1543   64]
 [ 214  179]]
Accuracy Score: 86.1 %

In [14]:
#Predicting result for Single Observation
print(model.predict(sc.transform([[502,0,0,42,8,159660.80,3,1,0,113931.57]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
[[ True]]

In [15]:
new_data = pd.DataFrame({'CreditScore':850,'Geography':2,'Gender':0,'Age':43,'Tenure':2,'Balance':125510.82,'NumOfProducts':1,'HasCrCard':1,'IsActiveMember':1,'EstimatedSalary':79084.10},index = [0])
Y_pred1 = model.predict(sc.transform(new_data)) > 0.5
print(Y_pred1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
[[False]]